version: "3"
services:
  app:
    build: ./app
    depends_on:
      - "db"
    command: ["./wait_for_mysql.sh"]
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
